plugins {
    id 'com.android.application'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file("key.properties")

if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace "com.erickwmiguel.livestage.junod"
    compileSdk 36

    defaultConfig {
        applicationId "com.erickwmiguel.livestage.junod"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile file(keystoreProperties["storeFile"])
                storePassword keystoreProperties["storePassword"]
                keyAlias keystoreProperties["keyAlias"]
                keyPassword keystoreProperties["keyPassword"]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    lint {
        disable 'All'
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    tasks.whenTaskAdded { task ->
        if (task.name == 'lintVitalAnalyzeRelease' || task.name == 'lintAnalyzeDebug') {
            task.enabled = false
        }
    }
}

dependencies {
}